### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by mbround18**

### CODE REVIEW

**Comment by mbround18** [comment]
@thakyZ im going to bump version and test

**Comment by mbround18** [comment]
Hey @thakyZ i would like to move from angularjs to react or something else. What are your thoughts?

**Comment by thakyZ** [comment]
I am so sorry for not replying it has been a busy past few months in my life. Umm I would have to say that would be ok but I would have to see what it would turn out like. I am still learning Ruby so it'll be something new at least. If you want to and you think it'll be easier on you or fix issues then sure go ahead

**Comment by mbround18** [comment]
Do you still actively use this?

**Comment by thakyZ** [comment]
@mbround18 Yes I do actively use this, but right now I have only one for a single instance, because as you know there is no way to set it up for multiple instances, and my admins can use it too then.

**Comment by mbround18** [comment]
Hey @thakyZ  i have started refactoring this, it will take me a bit but im cleaning up and commenting on the logic in the refactor branch

**Pull request closed without merging**
